import type { WizardStep } from "./wizard-types";

export const WIZARD_STEPS: WizardStep[] = [
  {
    id: "home",
    title: "Home Details",
    icon: "home",
    questions: [
      {
        id: "homeType",
        type: "select",
        title: "What type of home?",
        options: [
          { value: "single_family", label: "Single Family", description: "Detached house" },
          { value: "townhouse", label: "Townhouse", description: "Attached, multiple stories" },
          { value: "condo", label: "Condo / Apartment", description: "Unit in a larger building" },
          { value: "manufactured", label: "Manufactured / Mobile", description: "Factory-built home" },
        ],
        isVisible: () => true,
        getValue: (a) => a.homeDetails.homeType,
        setValue: (a, v) => ({ ...a, homeDetails: { ...a.homeDetails, homeType: v as typeof a.homeDetails.homeType } }),
      },
      {
        id: "squareFootage",
        type: "number",
        title: "Approximate square footage?",
        min: 200,
        max: 20000,
        step: 100,
        unit: "sq ft",
        placeholder: "e.g. 2000",
        isVisible: () => true,
        getValue: (a) => a.homeDetails.squareFootage,
        setValue: (a, v) => ({ ...a, homeDetails: { ...a.homeDetails, squareFootage: v } }),
      },
      {
        id: "climateZone",
        type: "select",
        title: "Which region best describes the home's climate?",
        description: "Sets the design temperatures for the sizing estimate.",
        options: [
          { value: "1", label: "Hot — tropical", description: "S. Florida, Hawaii" },
          { value: "2", label: "Hot", description: "Gulf Coast, S. Arizona, central Florida" },
          { value: "3", label: "Warm", description: "Georgia, N. Texas, S. California" },
          { value: "4", label: "Mixed", description: "Virginia, Maryland, Tennessee, Kansas" },
          { value: "5", label: "Cool", description: "Illinois, Ohio, New England coast" },
          { value: "6", label: "Cold", description: "Minnesota, Wisconsin, Vermont, Montana" },
          { value: "7", label: "Very cold", description: "Northern Minnesota, interior ND" },
          { value: "8", label: "Subarctic", description: "Interior Alaska" },
        ],
        isVisible: () => true,
        getValue: (a) => a.homeDetails.climateZone?.toString() ?? null,
        setValue: (a, v) => ({ ...a, homeDetails: { ...a.homeDetails, climateZone: parseInt(v) } }),
      },
      {
        id: "stories",
        type: "select",
        title: "How many stories?",
        options: [
          { value: "1", label: "1 Story" },
          { value: "2", label: "2 Stories" },
          { value: "3", label: "3+ Stories" },
        ],
        isVisible: (a) => a.homeDetails.homeType !== "condo",
        getValue: (a) => a.homeDetails.stories?.toString() ?? null,
        setValue: (a, v) => ({ ...a, homeDetails: { ...a.homeDetails, stories: parseInt(v) } }),
      },
      {
        id: "yearBuilt",
        type: "number",
        title: "Year built (approximate)?",
        min: 1900,
        max: 2026,
        placeholder: "e.g. 1995",
        isVisible: () => true,
        getValue: (a) => a.homeDetails.yearBuilt,
        setValue: (a, v) => ({ ...a, homeDetails: { ...a.homeDetails, yearBuilt: v } }),
      },
      {
        id: "insulationQuality",
        type: "select",
        title: "How would you rate your insulation?",
        description: "Older homes or drafty homes tend to have poor insulation.",
        options: [
          { value: "poor", label: "Poor", description: "Drafty, old windows, little attic insulation" },
          { value: "average", label: "Average", description: "Some insulation, typical for age" },
          { value: "good", label: "Good", description: "Well-sealed, modern insulation" },
        ],
        isVisible: () => true,
        getValue: (a) => a.homeDetails.insulationQuality,
        setValue: (a, v) => ({ ...a, homeDetails: { ...a.homeDetails, insulationQuality: v as typeof a.homeDetails.insulationQuality } }),
      },
    ],
  },
  {
    id: "existing",
    title: "Current System",
    icon: "wrench",
    questions: [
      {
        id: "projectType",
        type: "select",
        title: "What kind of project is this?",
        options: [
          { value: "replacement", label: "Replacement", description: "Replacing an existing system" },
          { value: "new_install", label: "New Installation", description: "No existing HVAC system" },
          { value: "addon", label: "Add-on", description: "Adding to an existing system (e.g. AC to existing furnace)" },
        ],
        isVisible: () => true,
        getValue: (a) => a.existingSystem.projectType,
        setValue: (a, v) => ({ ...a, existingSystem: { ...a.existingSystem, projectType: v as typeof a.existingSystem.projectType } }),
      },
      {
        id: "currentSystemType",
        type: "select",
        title: "What system do you currently have?",
        options: [
          { value: "central_ac", label: "Central AC + Furnace" },
          { value: "heat_pump", label: "Heat Pump" },
          { value: "furnace", label: "Furnace Only" },
          { value: "mini_split", label: "Mini Split / Ductless" },
          { value: "dual_fuel", label: "Dual Fuel (Heat Pump + Furnace)" },
        ],
        isVisible: (a) => a.existingSystem.projectType !== "new_install",
        getValue: (a) => a.existingSystem.currentSystemType,
        setValue: (a, v) => ({ ...a, existingSystem: { ...a.existingSystem, currentSystemType: v as typeof a.existingSystem.currentSystemType } }),
      },
      {
        id: "currentSystemAge",
        type: "number",
        title: "How old is your current system (years)?",
        min: 0,
        max: 50,
        placeholder: "e.g. 15",
        unit: "years",
        isVisible: (a) => a.existingSystem.projectType !== "new_install",
        getValue: (a) => a.existingSystem.currentSystemAge,
        setValue: (a, v) => ({ ...a, existingSystem: { ...a.existingSystem, currentSystemAge: v } }),
      },
      {
        id: "fuelType",
        type: "select",
        title: "What fuel source is available?",
        options: [
          { value: "natural_gas", label: "Natural Gas" },
          { value: "electric", label: "Electric Only" },
          { value: "propane", label: "Propane" },
          { value: "oil", label: "Oil" },
        ],
        isVisible: () => true,
        getValue: (a) => a.existingSystem.fuelType,
        setValue: (a, v) => ({ ...a, existingSystem: { ...a.existingSystem, fuelType: v as typeof a.existingSystem.fuelType } }),
      },
      {
        id: "ductworkCondition",
        type: "select",
        title: "What's the condition of your ductwork?",
        options: [
          { value: "good", label: "Good", description: "Well-sealed, insulated, no visible damage" },
          { value: "needs_repair", label: "Needs Repair", description: "Some leaks or damage" },
          { value: "needs_replacement", label: "Needs Replacement", description: "Severely damaged or undersized" },
          { value: "no_ducts", label: "No Ductwork", description: "Home doesn't have ducts" },
        ],
        isVisible: () => true,
        getValue: (a) => a.existingSystem.ductworkCondition,
        setValue: (a, v) => ({ ...a, existingSystem: { ...a.existingSystem, ductworkCondition: v as typeof a.existingSystem.ductworkCondition } }),
      },
    ],
  },
  {
    id: "desired",
    title: "New System",
    icon: "thermometer",
    questions: [
      {
        id: "systemType",
        type: "select",
        title: "What type of system do you want?",
        options: [
          { value: "central_ac", label: "Central AC + Furnace", description: "Traditional split system" },
          { value: "heat_pump", label: "Heat Pump", description: "Heats and cools, all-electric" },
          { value: "furnace", label: "Furnace Only", description: "Heating only" },
          { value: "mini_split", label: "Mini Split", description: "Ductless, zone-based" },
          { value: "dual_fuel", label: "Dual Fuel", description: "Heat pump + gas furnace backup" },
        ],
        isVisible: () => true,
        getValue: (a) => a.desiredSystem.systemType,
        setValue: (a, v) => ({ ...a, desiredSystem: { ...a.desiredSystem, systemType: v as typeof a.desiredSystem.systemType } }),
      },
      {
        id: "desiredFuelType",
        type: "select",
        title: "Fuel type for new system?",
        options: [
          { value: "natural_gas", label: "Natural Gas" },
          { value: "electric", label: "Electric" },
          { value: "propane", label: "Propane" },
        ],
        isVisible: (a) => a.desiredSystem.systemType === "furnace" || a.desiredSystem.systemType === "central_ac" || a.desiredSystem.systemType === "dual_fuel",
        getValue: (a) => a.desiredSystem.fuelType,
        setValue: (a, v) => ({ ...a, desiredSystem: { ...a.desiredSystem, fuelType: v as typeof a.desiredSystem.fuelType } }),
      },
      {
        id: "efficiencyTier",
        type: "select",
        title: "What efficiency level?",
        description: "Higher efficiency costs more upfront but saves on energy bills.",
        options: [
          { value: "standard", label: "Standard", description: "Meets minimum requirements, lowest upfront cost" },
          { value: "mid", label: "Mid-Efficiency", description: "Good balance of cost and savings" },
          { value: "high", label: "High Efficiency", description: "Maximum savings, highest upfront cost" },
        ],
        isVisible: () => true,
        getValue: (a) => a.desiredSystem.efficiencyTier,
        setValue: (a, v) => ({ ...a, desiredSystem: { ...a.desiredSystem, efficiencyTier: v as typeof a.desiredSystem.efficiencyTier } }),
      },
      {
        id: "zones",
        type: "select",
        title: "How many zones?",
        description: "More zones = more control, but higher cost.",
        options: [
          { value: "1", label: "1 Zone", description: "Whole home, single thermostat" },
          { value: "2", label: "2 Zones", description: "e.g. upstairs/downstairs" },
          { value: "3", label: "3+ Zones", description: "Room-by-room control" },
        ],
        isVisible: (a) => a.desiredSystem.systemType === "mini_split" || (a.homeDetails.stories ?? 1) > 1,
        getValue: (a) => a.desiredSystem.zones?.toString() ?? null,
        setValue: (a, v) => ({ ...a, desiredSystem: { ...a.desiredSystem, zones: parseInt(v) } }),
      },
    ],
  },
  {
    id: "additional",
    title: "Additional Work",
    icon: "clipboard-list",
    questions: [
      {
        id: "thermostat",
        type: "checkbox",
        title: "New smart thermostat?",
        description: "Nest, Ecobee, or similar.",
        isVisible: () => true,
        getValue: (a) => a.additionalWork.thermostat,
        setValue: (a, v) => ({ ...a, additionalWork: { ...a.additionalWork, thermostat: v } }),
      },
      {
        id: "ductworkModification",
        type: "checkbox",
        title: "Ductwork modifications needed?",
        description: "Extending, rerouting, or adding duct runs.",
        isVisible: (a) => a.existingSystem.ductworkCondition !== "no_ducts" && a.desiredSystem.systemType !== "mini_split",
        getValue: (a) => a.additionalWork.ductworkModification,
        setValue: (a, v) => ({ ...a, additionalWork: { ...a.additionalWork, ductworkModification: v } }),
      },
      {
        id: "electricalUpgrade",
        type: "checkbox",
        title: "Electrical panel upgrade needed?",
        description: "Required for some heat pump installations or older homes.",
        isVisible: () => true,
        getValue: (a) => a.additionalWork.electricalUpgrade,
        setValue: (a, v) => ({ ...a, additionalWork: { ...a.additionalWork, electricalUpgrade: v } }),
      },
      {
        id: "permitRequired",
        type: "checkbox",
        title: "Include permit costs?",
        description: "Most jurisdictions require permits for HVAC work.",
        isVisible: () => true,
        getValue: (a) => a.additionalWork.permitRequired,
        setValue: (a, v) => ({ ...a, additionalWork: { ...a.additionalWork, permitRequired: v } }),
      },
    ],
  },
];
